# Generated by Django 4.1 on 2022-10-11 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="books",
            name="book_img",
            field=models.ImageField(
                default="staic/img/groupK.png", upload_to="images/"
            ),
        ),
    ]
