# Generated by Django 4.1 on 2022-10-11 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_books_book_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="books",
            name="book_img",
            field=models.ImageField(
                default="static/img/groupK.png", upload_to="images/"
            ),
        ),
    ]
