# Generated by Django 4.1.2 on 2022-10-21 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_alter_books_book_img"),
    ]

    operations = [
        migrations.DeleteModel(name="Post",),
        migrations.AlterField(
            model_name="books",
            name="book_img",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
